import 'package:firebase_core/firebase_core.dart';

/// Central helper to determine if Firebase backend is available.
///
/// On web, Firebase.initializeApp requires FirebaseOptions generated by Dreamflow's
/// Firebase panel. If the app isn't connected yet, [Firebase.apps] will be empty
/// and services should avoid touching Firebase instances.
class BackendStatus {
  static bool get isFirebaseAvailable {
    try {
      return Firebase.apps.isNotEmpty;
    } catch (_) {
      return false;
    }
  }
}
